apiVersion: v1
kind: Service
metadata:
  labels:
    app: control-plane
  name: control-plane
  namespace: default
  annotations:
    'external-dns.alpha.kubernetes.io/ttl': "60"
    'external-dns.alpha.kubernetes.io/hostname': "${mcpDnsHostname}"
    'service.beta.kubernetes.io/aws-load-balancer-backend-protocol': "tcp"
    'service.beta.kubernetes.io/aws-load-balancer-ssl-cert': "${tlsCertArn}"
    'service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout': "3600"
    'service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled': "true"
    # Setting the value of this annotation to false does not work due to a bug in the aws controller
    # we just comment out this line if the aws zone is public. The bug is fixed in recent versions, so we should
    # be able to go back to specifying true/false once eks is updated
    ${isAwsZonePublic? "#" : ""}'service.beta.kubernetes.io/aws-load-balancer-internal': "true"
	'service.beta.kubernetes.io/aws-load-balancer-access-log-enabled': "true"
    'service.beta.kubernetes.io/aws-load-balancer-access-log-emit-interval': "2"  
    'service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name': "paxata-test-eks"
    'service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix': "access-logs/dev"
    
spec:
  type: LoadBalancer
  ports:
  - name: "8061"
    port: 8061
  - name: "5000"
    port: 5000
  selector:
    app: control-plane